# Generated by Django 3.2.7 on 2021-09-04 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('isInit', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ask', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='action',
            name='configAction',
        ),
        migrations.RemoveField(
            model_name='action',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='datas',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(to='AAPyppeteer.Project'),
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.AddField(
            model_name='block',
            name='blockConfig',
            field=models.ManyToManyField(to='AAPyppeteer.Action'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AAPyppeteer.question'),
        ),
        migrations.AddField(
            model_name='action',
            name='answer',
            field=models.ManyToManyField(to='AAPyppeteer.Answer'),
        ),
        migrations.AddField(
            model_name='project',
            name='core',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='core', to='AAPyppeteer.block'),
        ),
        migrations.AddField(
            model_name='project',
            name='init',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='init', to='AAPyppeteer.block'),
        ),
    ]
