# Generated by Django 3.2.7 on 2021-09-04 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0005_auto_20210904_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='core',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core', to='AAPyppeteer.block'),
        ),
        migrations.AlterField(
            model_name='project',
            name='init',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='init', to='AAPyppeteer.block'),
        ),
    ]
