# Generated by Django 3.2.7 on 2021-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0009_answer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='answers',
            field=models.ManyToManyField(blank=True, null=True, to='AAPyppeteer.Answer'),
        ),
        migrations.AlterField(
            model_name='block',
            name='blockConfig',
            field=models.ManyToManyField(blank=True, null=True, to='AAPyppeteer.Action'),
        ),
    ]
