# Generated by Django 3.2.7 on 2021-09-05 12:13

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0010_auto_20210905_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.CharField(default=builtins.input, max_length=200),
            preserve_default=False,
        ),
    ]
