# Generated by Django 3.2.7 on 2021-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0011_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nbPage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
