# Generated by Django 3.2.7 on 2021-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0012_project_nbpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datas',
            field=models.JSONField(default=list),
        ),
    ]
