# Generated by Django 3.2.7 on 2021-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0016_auto_20210907_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
