# Generated by Django 3.2.7 on 2021-09-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0017_block_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseaction',
            old_name='questions',
            new_name='elements',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='blockConfig',
            new_name='elements',
        ),
    ]
