# Generated by Django 3.2.7 on 2021-09-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0018_auto_20210907_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='answers',
            new_name='elements',
        ),
    ]
