# Generated by Django 3.2.7 on 2021-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0019_rename_answers_action_elements'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockconfigured',
            name='isAdvanced',
            field=models.BooleanField(default=False),
        ),
    ]
