# Generated by Django 3.2.7 on 2021-09-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0023_auto_20210909_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageProject',
        ),
    ]
