# Generated by Django 3.2.7 on 2021-09-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0024_rename_image_imageproject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageproject',
            unique_together=set(),
        ),
    ]
