# Generated by Django 3.2.7 on 2021-09-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0025_alter_imageproject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproject',
            name='name',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='imagesProject', to='AAPyppeteer.ImageProject'),
        ),
    ]
