# Generated by Django 3.2.7 on 2021-09-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0026_auto_20210909_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
