# Generated by Django 3.2.7 on 2021-09-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0028_action_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('datas', models.JSONField(default={})),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='elements',
            field=models.ManyToManyField(to='AAPyppeteer.Answer'),
        ),
        migrations.AlterField(
            model_name='block',
            name='elements',
            field=models.ManyToManyField(to='AAPyppeteer.Action'),
        ),
        migrations.AlterField(
            model_name='project',
            name='blocks',
            field=models.ManyToManyField(related_name='blocks', to='AAPyppeteer.BlockConfigured'),
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(related_name='imagesProject', to='AAPyppeteer.ImageProject'),
        ),
        migrations.CreateModel(
            name='DataBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('answers', models.JSONField(default={})),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AAPyppeteer.datablocktype')),
            ],
        ),
        migrations.AddField(
            model_name='blockconfigured',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AAPyppeteer.datablock'),
        ),
    ]
