# Generated by Django 3.2.7 on 2021-09-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0029_auto_20210912_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datablock',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='datablocktype',
            name='datas',
            field=models.JSONField(default=dict),
        ),
    ]
