# Generated by Django 3.2.7 on 2021-09-12 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0030_auto_20210912_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockconfigured',
            name='data',
        ),
        migrations.AddField(
            model_name='blockconfigured',
            name='dataIn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataIn', to='AAPyppeteer.datablock'),
        ),
        migrations.AddField(
            model_name='blockconfigured',
            name='dataOut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataOut', to='AAPyppeteer.datablock'),
        ),
    ]
