# Generated by Django 3.2.7 on 2021-09-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0032_datablock_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datablock',
            old_name='answers',
            new_name='datas',
        ),
        migrations.AddField(
            model_name='datablock',
            name='path',
            field=models.CharField(default=[], max_length=200),
            preserve_default=False,
        ),
    ]
