# Generated by Django 3.2.7 on 2021-09-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0033_auto_20210914_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockconfigured',
            name='datas',
            field=models.JSONField(default=dict),
        ),
    ]
