# Generated by Django 3.2.7 on 2021-09-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0034_alter_blockconfigured_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='datablock',
            name='requireFile',
            field=models.BooleanField(default=False),
        ),
    ]
