# Generated by Django 3.2.7 on 2021-09-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0035_datablock_requirefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datablock',
            name='requireFile',
        ),
        migrations.AddField(
            model_name='datablocktype',
            name='requireFile',
            field=models.BooleanField(default=False),
        ),
    ]
