# Generated by Django 3.2.7 on 2021-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0037_rename_user_id_datablock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datablock',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
