# Generated by Django 3.2.7 on 2021-09-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0038_alter_datablock_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='datablocktype',
            name='io',
            field=models.CharField(default='in', max_length=200),
        ),
    ]
