# Generated by Django 3.2.7 on 2021-09-15 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0039_datablocktype_io'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockconfigured',
            name='dataOut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataOut', to='AAPyppeteer.datablocktype'),
        ),
    ]
