# Generated by Django 3.2.7 on 2021-09-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0040_alter_blockconfigured_dataout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockconfigured',
            name='dataIn',
        ),
        migrations.RemoveField(
            model_name='blockconfigured',
            name='dataOut',
        ),
        migrations.AddField(
            model_name='blockconfigured',
            name='globalDatas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='globalDatas', to='AAPyppeteer.datablock'),
        ),
        migrations.AddField(
            model_name='blockconfigured',
            name='datasOut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasOut', to='AAPyppeteer.datablocktype'),
        ),
    ]
