# Generated by Django 3.2.7 on 2021-09-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0041_auto_20210915_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockconfigured',
            name='globalDatas',
        ),
        migrations.AddField(
            model_name='blockconfigured',
            name='datasIn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasIn', to='AAPyppeteer.datablock'),
        ),
        migrations.AddField(
            model_name='blockconfigured',
            name='isLinkedToNext',
            field=models.BooleanField(default=False),
        ),
    ]
