# Generated by Django 3.2.7 on 2021-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0042_auto_20210918_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockconfigured',
            name='datasOutUrl',
            field=models.JSONField(default='["static": [], "other": []]'),
        ),
    ]
