# Generated by Django 3.2.7 on 2021-09-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0043_blockconfigured_datasouturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockconfigured',
            name='datasOutUrl',
            field=models.JSONField(default=dict),
        ),
    ]
