# Generated by Django 3.2.7 on 2021-09-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0045_alter_blockconfigured_datasouturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockconfigured',
            name='datasOutUrl',
        ),
        migrations.AddField(
            model_name='project',
            name='datasOutUrl',
            field=models.JSONField(default=list),
        ),
    ]
