# Generated by Django 3.2.7 on 2021-09-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0046_auto_20210918_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='datablocktype',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
