# Generated by Django 3.2.7 on 2021-09-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AAPyppeteer', '0047_datablocktype_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockconfigured',
            name='datasOut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasOut', to='AAPyppeteer.datablock'),
        ),
    ]
